name: ${project.name}
author: bmlzootown
version: ${project.version}
main: ml.bmlzootown.CCVote
depend: [Votifier]
api-version: 1.13
permissions:
    ccvote.reload:
        default: op
commands:
     ccvote:
          description: See /ccvote for more info.